config/routes.rb
Rails.application.routes.draw do
  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        post '/create_post' => 'posts#create', as: :create_post
      end
      resources :posts, only: [:update, :destroy, :show]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save { self.role ||= :member }

  before_create :generate_auth_token

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def self.avatar_url(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
   before_filter :authenticate_user
   before_filter :authorize_user

   def show
     user = User.find(params[:id])
     render json: user.to_json, status: 200
   end

   def index
     users = User.all
     render json: users.to_json, status: 200
   end

   def update
     user = User.find(params[:id])

     if user.update_attributes(user_params)
       render json: user.to_json, status: 200
     else
       render json: {error: "User update failed", status: 400}, status: 400
     end
   end

   def create
     user = User.new(user_params)

     if user.valid?
       user.save!
       render json: user.to_json, status: 201
     else
       render json: {error: "User is invalid", status: 400}, status: 400
     end
   end

   private

   def user_params
     params.require(:user).permit(:name, :email, :password, :role)
   end

 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.name}!"
      redirect_to root_path
      create_session(@user)
    else
      flash[:error] = "There was an error creating your account. Please try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end  

end

app/helpers/users_helper.rb
module UsersHelper

  def render_user_posts(user)
    if user.posts.count > 0
      render user.posts
    else
      "#{user.name} has not submitted any posts yet."
    end
  end

  def render_user_comments(user)
    if user.comments.count > 0
      render user.comments
    else
      "#{user.name} has not submitted any comments yet."
    end
  end

end

app/views/users/_favorite.html.erb
<div class="media">
  <div class="media-body">
    <%= link_to favorite.post.title, topic_post_path(favorite.post.topic, favorite.post) %>
    <%= image_tag User.avatar_url(@user, 20) %>
    <small>(Votes: <%= favorite.post.votes.count %></small>
    <small>Comments: <%= favorite.post.comments.count %>)</small>
  </div>
</div>

app/views/users/confirm.html.erb
<h2>Sign Up Confirmation</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user do |f| %>
        <h4>Are you sure these values are correct?</h4>
        <p>Email: <%= @user.email %></p>
        <p>Name: <%= @user.name %></p>
        <%= f.hidden_field :email, :value => @user.email %>
        <%= f.hidden_field :name, :value => @user.name %>
        <%= f.hidden_field :password, :value => @user.password %>
        <%= f.hidden_field :password_confirmation, :value => @user.password_confirmation %>
        <div class="form-group">
          <%= f.submit "Yes", class: 'btn btn-success' %>
          <%= link_to "No", new_user_path, class: 'btn btn-default' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/users/new.html.erb
<h2>Sign up</h2>

 <div class="row">
   <div class="col-md-8">
     <%= form_for @user, :url => { :action => :confirm } do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4>There are <%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>
       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/users/show.html.erb
<div class="row">
   <div class="col-md-8">
     <div class="media">
       <br />
        <% avatar_url = User.avatar_url(@user, 128) %>
       <% unless avatar_url.nil? %>
         <div class="media-left">
           <%= image_tag avatar_url, class: 'media-object' %>
         </div>
       <% end %>
       <div class="media-body">
         <h2 class="media-heading"><%= @user.name %></h2>
         <small>
           <%= pluralize(@user.posts.count, 'post') %>,
           <%= pluralize(@user.comments.count, 'comment') %>
         </small>
       </div>
     </div>
   </div>
 </div>

 <h2>Posts</h2>
 <%= render_user_posts(@user) %>

 <h2>Comments</h2>
 <%= render_user_comments(@user) %>

 <h2>Favorites</h2>
  <div class="row">
    <div class="col-md-8">
      <%= render partial: 'users/favorite', collection: @user.favorites %>
    </div>
  </div>